"""fix posts table

Revision ID: d64b81df3e4e
Revises: cfa2a69bdda6
Create Date: 2018-04-11 12:17:29.730577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64b81df3e4e'
down_revision = 'cfa2a69bdda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=500), nullable=True))
    op.drop_column('post', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('username', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
